export const API_CALLS_IN_PROGRESS = {
    BEGIN_CALL: 'API BEGIN CALL',
    CALL_ERROR: 'API CALL ERROR'
};

export const POPULAR_MEDIAS = {
    FILTER_PROPERTIES: 'FILTER PROPERTIES POPULAR MEDIAS DISCOVER',
    LOAD_SUCCESS: 'LOAD POPULAR MEDIAS DISCOVER SUCCESS',
    LOAD_FAILURE: 'LOAD POPULAR MEDIAS DISCOVER FAILURE'
};

export const TOP_RATED_MEDIAS = {
    FILTER_PROPERTIES: 'FILTER PROPERTIES TOP_RATED MEDIAS DISCOVER',
    LOAD_SUCCESS: 'LOAD TOP_RATED MEDIAS DISCOVER SUCCESS',
    LOAD_FAILURE: 'LOAD TOP_RATED MEDIAS DISCOVER FAILURE'
};

export const DETAILS_MEDIA = {
    FILTER_PROPERTIES: 'FILTER PROPERTIES DETAILS MEDIA',
    LOAD_SUCCESS: 'LOAD DETAILS SUCCESS',
    LOAD_FAILURE: 'LOAD DETAILS FAILURE'
};

export const CREDITS_MEDIA = {
    FILTER_PROPERTIES: 'FILTER PROPERTIES CREDITS MEDIA',
    LOAD_SUCCESS: 'LOAD CREDITS SUCCESS',
    LOAD_FAILURE: 'LOAD CREDITS FAILURE'
};

export const RECOMMENDATIONS_MEDIA = {
    FILTER_PROPERTIES: 'FILTER PROPERTIES RECOMMENDATIONS MEDIAS',
    LOAD_SUCCESS: 'LOAD RECOMMENDATIONS MEDIAS SUCCESS',
    LOAD_FAILURE: 'LOAD RECOMMENDATIONS MEDIAS FAILURE'
};