export const POPULAR_MEDIAS = {
    FILTER_PROPERTIES: 'FILTER PROPERTIES POPULAR MEDIAS DISCOVER',
    LOAD_SUCCESS: 'LOAD POPULAR MEDIAS DISCOVER SUCCESS',
    LOAD_FAILURE: 'LOAD POPULAR MEDIAS DISCOVER FAILURE'
};


export const TOP_RATED_MEDIAS = {
    FILTER_PROPERTIES: 'FILTER PROPERTIES TOP_RATED MEDIAS DISCOVER',
    LOAD_SUCCESS: 'LOAD TOP_RATED MEDIAS DISCOVER SUCCESS',
    LOAD_FAILURE: 'LOAD TOP_RATED MEDIAS DISCOVER FAILURE'
};